version: "3.8"

networks:
    portfolio-app-network:
  
volumes:
    portfolio-app-volume:

services:

    portfolio-app-react:
        stdin_open: true
        container_name: portfolio-app-react
        build:
            context: .
            dockerfile: ./frontend/docker/node/Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - "/app/node_modules"
            - "./frontend/:/app"
        networks:
            - portfolio-app-network

    portfolio-app-nginx:
        image: nginx:stable-alpine
        container_name: portfolio-app-nginx
        ports:
            - "8080:80"
        volumes:
            - ./backend/:/var/www/app
            - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - portfolio-app-php
            - portfolio-app-mysql
        networks:
            - portfolio-app-network

    portfolio-app-mysql:
        image: mysql:8.0
        container_name: portfolio-app-mysql
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: portfolio-appdb
            MYSQL_ROOT_PASSWORD: secret
        command: "--log-bin-trust-function-creators=1"
        volumes:
            - portfolio-app-volume:/var/lib/mysql
        networks:
            - portfolio-app-network
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE

    portfolio-app-php:
        build:
            context: .
            dockerfile: ./backend/docker/php/Dockerfile
        image: portfolio-app-php
        container_name: portfolio-app-php
        tty: true
        working_dir: /var/www/portfolio-app/
        volumes:
            - ./backend/:/var/www/portfolio-app
        #command: /bin/sh -C "./entrypoint.dev.sh"
        depends_on:
            - portfolio-app-mysql
        expose:
            - 9000
        networks:
            - portfolio-app-network