version: "3.8"

services:
# FIXME: this stuff is broken, need to iron out ports and 
    app-react:
        stdin_open: true
        container_name: "app-react"
        build:
            context: .
            dockerfile: /frontend/Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - "frontend/node_modules"
            - "frontend/:/app"

    app-nginx:
        image: nginx:stable-alpine
        container_name: app-nginx
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app-php
            - app-mysql
        networks:
            - app-network

    app-mysql:
        image: mysql:8.0
        container_name: app-mysql
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: appdb
            MYSQL_ROOT_PASSWORD: secret
        command: "--log-bin-trust-function-creators=1"
        volumes:
            - app-volume:/var/lib/mysql
        networks:
            - app-network
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE

    app-php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: app-php
        container_name: app-php
        tty: true
        working_dir: /var/www/app/
        volumes:
            - ./:/var/www/app
        #command: /bin/sh -C "./entrypoint.dev.sh"
        depends_on:
            - app-mysql
        expose:
            - 9000
        networks:
            - app-network